// Generated by tools/generate_design_tokens.py. Do not edit.
package com.lstepnio.egauge.core.designsystem

import androidx.compose.ui.graphics.Color

object EGaugeTokens {
    object Dark {
        val background = Color(0xFF111315)
        val surface = Color(0xFF1C1F21)
        val surfaceRaised = Color(0xFF282C2E)
        val onSurface = Color(0xFFF3F4EF)
        val muted = Color(0xFFB5BCB8)
        val primary = Color(0xFF00FF70)
        val onPrimary = Color(0xFF00331B)
        val primaryContainer = Color(0xFF004B2B)
        val onPrimaryContainer = Color(0xFF00FF70)
        val outline = Color(0xFF454B47)
        val warning = Color(0xFFFF8A00)
        val critical = Color(0xFFFF1744)
        val success = Color(0xFF00FF70)
        val gauge = Color(0xFF05080A)
        val gaugeText = Color(0xFFE4EAED)
        val gaugeMuted = Color(0xFF9CAAB2)
        val gaugeTrack = Color(0xFF1B2A30)
        val gaugeAccent = Color(0xFF00FF70)
    }
    object Light {
        val background = Color(0xFFF5F6EF)
        val surface = Color(0xFFFFFFFF)
        val surfaceRaised = Color(0xFFE9ECE3)
        val onSurface = Color(0xFF1A1D19)
        val muted = Color(0xFF525A50)
        val primary = Color(0xFF007A49)
        val onPrimary = Color(0xFFFFFFFF)
        val primaryContainer = Color(0xFFB5FFD2)
        val onPrimaryContainer = Color(0xFF003E25)
        val outline = Color(0xFFC6CDC0)
        val warning = Color(0xFF9B3F00)
        val critical = Color(0xFFB00028)
        val success = Color(0xFF007A49)
        val gauge = Color(0xFF05080A)
        val gaugeText = Color(0xFFE4EAED)
        val gaugeMuted = Color(0xFF9CAAB2)
        val gaugeTrack = Color(0xFF1B2A30)
        val gaugeAccent = Color(0xFF00FF70)
    }
    object Spacing {
        const val xs = 4
        const val sm = 8
        const val md = 16
        const val lg = 24
        const val xl = 32
        const val xxl = 48
    }
    object Radius {
        const val control = 24
        const val card = 28
        const val hero = 36
        const val pill = 100
    }
    object Type {
        const val body = 16
        const val label = 14
        const val title = 32
        const val headline = 24
        const val value = 64
    }
    object Motion {
        const val feedback = 120
        const val transition = 240
    }
    object Layout {
        const val touchTarget = 48
        const val railBreakpoint = 600
        const val paneBreakpoint = 840
        const val contentMax = 1200
    }
}
