#!/usr/bin/env python3
"""Generate Android and browser tokens from the shared design palette."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    tokens = json.loads((ROOT / "design/tokens.json").read_text())
    android = tokens["android"]
    kotlin = ["// Generated by tools/generate_design_tokens.py. Do not edit.",
              "package com.lstepnio.egauge.core.designsystem", "", "import androidx.compose.ui.graphics.Color", "",
              "object EGaugeTokens {"]
    css = ["/* Generated by tools/generate_design_tokens.py. */", ":root {"]
    css += [f"  --{name}: {value};" for name, value in tokens["color"].items()]
    css += ["}"]
    for theme, roles in android["color"].items():
        kotlin.append(f"    object {theme.title()} {{")
        kotlin += [f"        val {key} = Color(0xFF{value[1:]})" for key, value in roles.items()]
        kotlin.append("    }")
        css.append(f'[data-theme="{theme}"] {{')
        css += [f"  --{key}: {value};" for key, value in roles.items()]
        css.append("}")
    for group in ("spacing", "radius", "type", "motion", "layout"):
        kotlin.append(f"    object {group.title()} {{")
        kotlin += [f"        const val {key} = {value}" for key, value in android[group].items()]
        kotlin.append("    }")
    kotlin += ["}", ""]
    css.append(":root {")
    for group in ("spacing", "radius", "type", "motion", "layout"):
        css += [f"  --{group}-{key}: {value}{'ms' if group == 'motion' else 'px'};"
                for key, value in android[group].items()]
    css += ["}", ""]
    fixtures = json.loads((ROOT / "design/fixtures/ui-states.json").read_text())
    fixture_lines = ["// Generated from design/fixtures/ui-states.json. Do not edit.",
        "package com.lstepnio.egauge.core.designsystem", "", "object ComponentFixtures {", "    val all = listOf("]
    for fixture in fixtures:
        tone = fixture["id"].title()
        if tone == "Default": tone = "Neutral"
        args = ", ".join(json.dumps(fixture[key], ensure_ascii=False) for key in ("id", "title", "detail", "value"))
        fixture_lines.append(f"        ComponentFixture({args}, StatusTone.{tone}),")
    fixture_lines += ["    )", "}", ""]
    return {
        ROOT / "android/core/designsystem/src/main/java/com/lstepnio/egauge/core/designsystem/GeneratedFixtures.kt": "\n".join(fixture_lines),
        ROOT / "android/core/designsystem/src/main/java/com/lstepnio/egauge/core/designsystem/GeneratedTokens.kt": "\n".join(kotlin),
        ROOT / "design/prototype/tokens.css": "\n".join(css),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, expected in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                raise SystemExit(f"Generated tokens are stale: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
    print("PASS: Android and browser design tokens match design/tokens.json")


if __name__ == "__main__":
    main()
