"""Generate editor metadata and wire definitions from one catalog. Use --check in CI."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'contracts/reading-catalog.json'
KOTLIN = ROOT / 'android/app/src/main/java/com/lstepnio/egauge/ReadingCatalog.kt'
TEMPLATE = ROOT / 'android/app/src/main/assets/numeric_config_template.json'


def generated():
    rows = json.loads(CATALOG.read_text())['readings']
    assert len({r['id'] for r in rows}) == len(rows)
    assert len({r['definition']['id'] for r in rows}) == len(rows)
    template = json.loads(TEMPLATE.read_text())
    template['definitions'] = [r['definition'] for r in rows]
    q = lambda value: json.dumps(value, ensure_ascii=False)
    lines = ['package com.lstepnio.egauge', '', '// Generated by tools/generate_reading_catalog.py. Edit contracts/reading-catalog.json.', 'val readingCatalog: List<PidExample> = listOf(']
    for row in rows:
        d = row['definition']; source = 'TCM' if d['request']['service'] == '22' else 'ECM'
        unit = {'degC': '°C', 'kph': 'km/h', 'gear': ''}.get(d['unit'], d['unit'])
        fields = [row['id'], row['name'], source, d['request']['service']+' '+d['request']['identifier'], unit, row['sample'],
                  d['provenance']['source'] if source == 'TCM' else 'Example only; vehicle support varies', row['category'], row['gaugeLabel'], d['id']]
        lines.append('    PidExample('+', '.join(map(q, fields))+f", {float(d['range']['min'])}, {float(d['range']['max'])}, {q(row['alertKind'])}, {row['configurationVersion']}),")
    lines += [')', '', 'val gearPositions = linkedMapOf(13.0 to "P", 11.0 to "R", 0.0 to "N",', '    1.0 to "1", 2.0 to "2", 3.0 to "3", 4.0 to "4", 5.0 to "5", 6.0 to "6", 7.0 to "7", 8.0 to "8")', '', 'fun readingBounds(id: String): ClosedFloatingPointRange<Double> =', '    readingCatalog.first { it.id == id }.let { it.minimum..it.maximum }', '', 'fun alertNumber(value: Double): String = java.math.BigDecimal.valueOf(value).stripTrailingZeros().toPlainString()', '']
    return {KOTLIN: '\n'.join(lines), TEMPLATE: json.dumps(template, separators=(',', ':'), ensure_ascii=False)+'\n'}


def run(check=False):
    for path, content in generated().items():
        if check:
            assert path.read_text() == content, f'Stale generated catalog: {path.relative_to(ROOT)}'
        else:
            path.write_text(content)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true')
    run(parser.parse_args().check)
